######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 7 01:54:34 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += zenwriter.h
FORMS += zenwriter.ui
SOURCES += main.cpp zenwriter.cpp
RESOURCES += zenwriter.qrc
