######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 22 06:20:36 2011
######################################################################

QT += phonon
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += zenwriter.h
FORMS += zenwriter.ui
SOURCES += main.cpp zenwriter.cpp
RESOURCES += zenwriter.qrc
